### ISSUE TITLE
How to prepare our own data

### ISSUE THREAD

**Issue by asssssasssssin** [tkipf/gcn#45]
Hi, everyone. I have a question. If I want to use our own datasets, what is the format of datasets. And what are the variables corresponding to "load_data()".  Thank you.

**Comment by tkipf** [comment]
It's literally as simple as this:

In order to use your own data, you have to provide
- an N by N adjacency matrix (N is the number of nodes),
- an N by D feature matrix (D is the number of features per node), and
- an N by E binary label matrix (E is the number of classes).

Have a look at the format of these matrices in the `load_data()` function to get a feeling for what they look like :-)

**Comment by guotong1988** [comment]
THX!

**Comment by AnnemSony** [comment]
Hi Every one,
I have an Adjacency Matrix Dataset(each file is each patient brain image converted to a matrix), what changes do I need to follow before applying the GNN model?
Can I directly split the dataset into train and test following the GNN model or do I need to perform any sort of preprocessing tasks?
Thank you!
