### ISSUE TITLE
How to handle the graph data with temporal changes?

### ISSUE THREAD

**Issue by yanglin-jason** [tkipf/gcn#46]
I'm handling a little bit different problem with gcn:

Given a graph of N nodes, I have serval temporal slice data, say s_0, s_1, s_2, ..., s_t, each of which includes the nodes' features X_t and the corresponding labels L_t at a time t (For each time slice, the graph structure does not change)

The task is to predict the label of each node at a given time t+1. 

In this case, I was wondering:
1. If I understand correctly, current gcn implementation can only handle one graph in an epoch. How can I handle the multiple "temporal" graphs and corresponding data properly?
2. I notice that the graph labels actually change over time. How can I model such a temporal evolving in gcn?

Any suggestion will be appreciated.

**Comment by tkipf** [comment]
You can either simply concatenate all the features for all time steps and
also append all the labels from previous time steps as features and use the
GCN model as is. Otherwise a simple modification would be to include a
temporal recurrency using eg an LSTM on top of the input feature vectors or
even at every layer of the model. I expect the first option to do
reasonably well, though.

**Comment by yanglin-jason** [comment]
Thanks a lot!
