### ISSUE TITLE
Support for the multiple gcn filters

### ISSUE THREAD

**Issue by yanglin-jason** [tkipf/gcn#47]
Hi, Kipf, thanks for sharing us such a great work.

I'm using gcn to perform a regression work on my dataset, in which I have around 500 nodes and 153 features.  The performance is not good even for the training set (R^2 = 0.4)

I was wondering:

1. Classical CNN models (AlexNet, VGG) often uses multiple filters to extract different patterns, but the current implementation of GCN, if I understand correctly, only uses one graphConv filter. Do you think multiple gcn filters can help?

2. If yes, how can I add more filters?

**Comment by tkipf** [comment]
You can try the model from our ICML 2018 paper:
https://github.com/ethanfetaya/NRI - the graph neural network we use there
has a much higher capacity and typically performs better in cases where you
have enough data (otherwise it would easily overfit). In the low-data
regime the GCN model from this repository here should do fine.

**Comment by yanglin-jason** [comment]
Thanks a lot! I will have a try.

**Comment by guotong1988** [comment]
Thx!
